export const ROLE = {
  ADMIN_MANAGER: 'ADMIN_MANAGER',
  ADMIN_TECH: 'ADMIN_TECH',
  MANAGER: 'MANAGER',
  TECH: 'TECH',
  MAGASIN: 'MAGASIN',
  COORDINATOR: 'COORDINATOR',
};

export enum Role {
  ADMIN_MANAGER = 'ADMIN_MANAGER',
  ADMIN_TECH = 'ADMIN_TECH',
  MANAGER = 'MANAGER',
  TECH = 'TECH',
  MAGASIN = 'MAGASIN',
  COORDINATOR = 'COORDINATOR',
}

export const CLIENT_TYPE = {
  CLIENT: 'CLIENT',
  COMPANY: 'COMPANY',
};
